package com.ATeam.twoDotFiveD;

import junit.framework.TestCase;

/**
 * The class <code>TwoDotFiveDTest</code> contains tests for the class {@link
 * <code>TwoDotFiveD</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 1/24/12 7:12 PM
 *
 * @author Tokume
 *
 * @version $Revision$
 */
public class TwoDotFiveDTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public TwoDotFiveDTest(String name) {
		super(name);
	}

	/**
	 * Run the void main(String[]) method test
	 */
	public void testMain() {
		//fail("Newly generated method - fix or disable");
		// add test code here
		String[] args = null;
		TwoDotFiveD.main(args);
		assertTrue(true);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames =
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = true
 * methods =
 * package = com.ATeam.twoDotFiveD
 * package.sourceFolder = twoDotFiveD/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = TwoDotFiveDTest
 * testClassType = com.ATeam.twoDotFiveD.TwoDotFiveD
 */