package com.ATeam.twoDotFiveD.event;

import com.ATeam.twoDotFiveD.entity.Player;
import com.ATeam.twoDotFiveD.event.player.PlayerListener;
import com.ATeam.twoDotFiveD.event.player.PlayerMoveEvent;

import junit.framework.TestCase;

/**
 * The class <code>PlayerListenerTest</code> contains tests for the class
 * {@link <code>PlayerListener</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 1/30/12 2:35 PM
 *
 * @author Tokume
 *
 * @version $Revision$
 */
public class PlayerListenerTest extends TestCase {
	private boolean caught;
	private Dispatcher dispatcher;
	private PlayerListener fixture;

	/**
	 * Construct new test instance
	 *
	 * @param name
	 *            the test name
	 */
	public PlayerListenerTest(String name) {
		super(name);
		//Initialize variables
		dispatcher = new Dispatcher();
		caught = false;
		fixture = new PlayerListener() {
			public void onPlayerMove(PlayerMoveEvent event) {
				if (event != null) {
					caught = true;
				}
			}
		};

	}

	/**
	 * Run the void onPlayerMove(PlayerMoveEvent) method test
	 */
	public void testOnPlayerMove() {
		//Register listener
		dispatcher.registerListener(Event.Type.PLAYER_MOVE, fixture);
		//Generate event
		PlayerMoveEvent playerMoveEvent = new PlayerMoveEvent(new Player());
		dispatcher.notify(playerMoveEvent);
		if(!caught)
		{
			fail("Did not catch the event.");
		}
		assertTrue(true);
	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = false createTearDown = false createTestFixture = false
 * createTestStubs = true methods = package = com.ATeam.twoDotFiveD.event
 * package.sourceFolder = twoDotFiveD/src/test/java superclassType =
 * junit.framework.TestCase testCase = PlayerListenerTest testClassType =
 * com.ATeam.twoDotFiveD.event.player.PlayerListener
 */