//package com.ATeam.twoDotFiveD.event;
//
//import com.ATeam.twoDotFiveD.entity.Entity;
//import com.ATeam.twoDotFiveD.event.player.PlayerMoveEvent;
//
//import junit.framework.TestCase;
//
///**
// * The class <code>EventTest</code> contains tests for the class {@link
// * <code>Dispatcher</code>}
// *
// * @pattern JUnit Test Case
// *
// * @generatedBy CodePro at 1/30/12 2:18 PM
// *
// * @author Tokume
// *
// * @version $Revision$
// */
//public class PlayerMoveEventTest extends TestCase
//{
//	private PlayerMoveEvent event;
//	private Entity player;
//	/**
//	 * Construct new test instance
//	 *
//	 * @param name the test name
//	 */
//	public PlayerMoveEventTest(String name)
//	{
//		super(name);
//		player = new Entity();
//		event = new PlayerMoveEvent(player);
//	}
//
//	/**
//	 * Test constructor for PlayerMoveEvent
//	 */
//	public void testPlayerMoveEventConstructor()
//	{
//
//		if(!event.getType().equals(Event.Type.PLAYER_MOVE))
//		{
//			fail("The event is not of the correct type.");
//		}
//		if(!event.getName().equals(event.getClass().getName()))
//		{
//			fail("The event does not have the correct name.");
//		}
//		if(!event.getType().getCategory().equals(Event.Category.PLAYER))
//		{
//			fail("The event does not have the correct category.");
//		}
//		if(!event.getType().getEventClass().equals(event.getClass()))
//		{
//			fail("The event type does not have the correct class.");
//		}
//		assertTrue(true);
//	}
//
//	public void testRetrievePlayerFromEvent()
//	{
//		if(!event.getPlayer().equals(player))
//		{
//			fail("Event's player does not match player given.");
//		}
//		assertTrue(true);
//	}
//	
//	public void testModifyPlayerAfterEvent()
//	{
//		player = new Entity();
//		if(event.getPlayer().equals(player))
//		{
//			fail("The event's player should not be modifiable.");
//		}
//		assertTrue(true);
//	}
//}
//
//
///*$CPS$ This comment was generated by CodePro. Do not edit it.
// * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
// * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
// * additionalTestNames =
// * assertTrue = false
// * callTestMethod = true
// * createMain = false
// * createSetUp = false
// * createTearDown = false
// * createTestFixture = false
// * createTestStubs = false
// * methods =
// * package = com.ATeam.twoDotFiveD.event
// * package.sourceFolder = twoDotFiveD/src/test/java
// * superclassType = junit.framework.TestCase
// * testCase = EventTest
// * testClassType = com.ATeam.twoDotFiveD.event.Dispatcher
// */